worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    client_max_body_size 20M;
    access_log /dev/stdout main;
    error_log  /dev/stderr warn;

    gzip on;
    gzip_types text/plain application/xml text/css application/json application/javascript;
    gzip_min_length 1024;

    # Redirect HTTP to HTTPS
    server {
        listen 80;
        server_name www.davidka.co.il davidka.co.il;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name www.davidka.co.il davidka.co.il;

        ssl_certificate      /app/ssl/furman.pem;
        ssl_certificate_key  /app/ssl/furman.key;

        # Security headers
        add_header X-Content-Type-Options nosniff;
        add_header X-Frame-Options DENY;
        add_header X-XSS-Protection "1; mode=block";

        location /generate-pdf {
        proxy_pass http://api:8000;

        add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0";
        add_header Pragma "no-cache";
        add_header Expires 0;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

        location / {
            proxy_pass http://api:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /static/ {
            alias /static/;
            autoindex off;
            add_header Cache-Control "public, max-age=86400";
        }

        location /uploads/ {
            alias /app/uploads/;
            autoindex off;
            add_header Cache-Control "public, max-age=86400";
        }
    }
}